/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ApiKey = IDL.Record({
  'id' : IDL.Text,
  'token' : IDL.Text,
  'ownerId' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileMetadata = IDL.Record({
  'id' : IDL.Text,
  'ownerId' : IDL.Principal,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'createdAt' : Time,
  'size' : IDL.Nat,
  'updatedAt' : Time,
  'parentId' : IDL.Opt(IDL.Text),
});
export const FolderMetadata = IDL.Record({
  'id' : IDL.Text,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'parentId' : IDL.Opt(IDL.Text),
});
export const InviteCode = IDL.Record({
  'expiresAt' : IDL.Opt(Time),
  'code' : IDL.Text,
  'usedBy' : IDL.Vec(IDL.Principal),
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'usedCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'maxUses' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccessCheckResult = IDL.Variant({
  'NeedsInvite' : IDL.Null,
  'Approved' : IDL.Null,
  'Admin' : IDL.Null,
  'PendingApproval' : IDL.Null,
});
export const FileSystemItem = IDL.Variant({
  'file' : FileMetadata,
  'folder' : FolderMetadata,
});
export const AdminInfo = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'role' : UserRole,
});
export const StorageStats = IDL.Record({
  'totalFiles' : IDL.Nat,
  'totalFolders' : IDL.Nat,
  'totalEncryptedFiles' : IDL.Nat,
  'frontendCanisterId' : IDL.Text,
  'appVersion' : IDL.Text,
  'totalStorageBytes' : IDL.Nat,
  'backendCanisterId' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const FileMove = IDL.Record({
  'id' : IDL.Text,
  'isFolder' : IDL.Bool,
  'newParentId' : IDL.Opt(IDL.Text),
});
export const InviteResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const FolderSearchResults = IDL.Record({
  'files' : IDL.Vec(FileMetadata),
  'folders' : IDL.Vec(FolderMetadata),
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__adminPrincipal' : IDL.Func([], [IDL.Reserved], ['query']),
  '__apiKeys' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, ApiKey))],
      ['query'],
    ),
  '__appVersion' : IDL.Func([], [IDL.Text], ['query']),
  '__approvalState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__backendCanisterId' : IDL.Func([], [IDL.Text], ['query']),
  '__cliFileBytes' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Nat8)))],
      ['query'],
    ),
  '__encryptedFiles' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  '__files' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, FileMetadata))],
      ['query'],
    ),
  '__firstAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  '__folders' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, FolderMetadata))],
      ['query'],
    ),
  '__frontendCanisterId' : IDL.Func([], [IDL.Text], ['query']),
  '__inviteCodes' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, InviteCode))],
      ['query'],
    ),
  '__nextApiKeyId' : IDL.Func([], [IDL.Nat], ['query']),
  '__nextFolderId' : IDL.Func([], [IDL.Nat], ['query']),
  '__tokenCounter' : IDL.Func([], [IDL.Nat], ['query']),
  '__userProfiles' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addFile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), ExternalBlob, IDL.Bool],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAccess' : IDL.Func([], [AccessCheckResult], ['query']),
  'createFolder' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Text], []),
  'deleteApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteFile' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteFolder' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'generateApiKey' : IDL.Func([IDL.Text], [IDL.Text], []),
  'generateInviteCode' : IDL.Func(
      [IDL.Opt(IDL.Int), IDL.Opt(IDL.Nat)],
      [IDL.Text],
      [],
    ),
  'getAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getAllFolders' : IDL.Func([], [IDL.Vec(FolderMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFile' : IDL.Func([IDL.Text], [IDL.Opt(FileMetadata)], ['query']),
  'getFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getFolder' : IDL.Func([IDL.Text], [IDL.Opt(FolderMetadata)], ['query']),
  'getFolderContents' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(FileSystemItem)],
      ['query'],
    ),
  'getMembers' : IDL.Func([], [IDL.Vec(AdminInfo)], ['query']),
  'getStorageStats' : IDL.Func([], [StorageStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([], [UserRole], ['query']),
  'http_request' : IDL.Func(
      [
        IDL.Record({
          'url' : IDL.Text,
          'method' : IDL.Text,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        }),
      ],
      [
        IDL.Record({
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          'upgrade' : IDL.Opt(IDL.Bool),
          'status_code' : IDL.Nat16,
        }),
      ],
      ['query'],
    ),
  'http_request_update' : IDL.Func(
      [
        IDL.Record({
          'url' : IDL.Text,
          'method' : IDL.Text,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        }),
      ],
      [
        IDL.Record({
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          'status_code' : IDL.Nat16,
        }),
      ],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isUsernameUnique' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'listApiKeys' : IDL.Func([], [IDL.Vec(ApiKey)], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'moveItem' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text), IDL.Bool], [], []),
  'moveItems' : IDL.Func([IDL.Vec(FileMove)], [], []),
  'redeemInviteCode' : IDL.Func([IDL.Text], [InviteResult], []),
  'removeMember' : IDL.Func([IDL.Principal], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'revokeInviteCode' : IDL.Func([IDL.Text], [InviteResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchFiles' : IDL.Func([IDL.Text], [IDL.Vec(FileMetadata)], ['query']),
  'searchFoldersInSubtree' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [FolderSearchResults],
      ['query'],
    ),
  'searchSubtree' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(FileSystemItem)],
      ['query'],
    ),
  'setAdmin' : IDL.Func([IDL.Principal], [InviteResult], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setBackendCanisterId' : IDL.Func([IDL.Text], [], []),
  'setFrontendCanisterId' : IDL.Func([IDL.Text], [], []),
  'validateInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ApiKey = IDL.Record({
    'id' : IDL.Text,
    'token' : IDL.Text,
    'ownerId' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileMetadata = IDL.Record({
    'id' : IDL.Text,
    'ownerId' : IDL.Principal,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'createdAt' : Time,
    'size' : IDL.Nat,
    'updatedAt' : Time,
    'parentId' : IDL.Opt(IDL.Text),
  });
  const FolderMetadata = IDL.Record({
    'id' : IDL.Text,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'parentId' : IDL.Opt(IDL.Text),
  });
  const InviteCode = IDL.Record({
    'expiresAt' : IDL.Opt(Time),
    'code' : IDL.Text,
    'usedBy' : IDL.Vec(IDL.Principal),
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'usedCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'maxUses' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccessCheckResult = IDL.Variant({
    'NeedsInvite' : IDL.Null,
    'Approved' : IDL.Null,
    'Admin' : IDL.Null,
    'PendingApproval' : IDL.Null,
  });
  const FileSystemItem = IDL.Variant({
    'file' : FileMetadata,
    'folder' : FolderMetadata,
  });
  const AdminInfo = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'role' : UserRole,
  });
  const StorageStats = IDL.Record({
    'totalFiles' : IDL.Nat,
    'totalFolders' : IDL.Nat,
    'totalEncryptedFiles' : IDL.Nat,
    'frontendCanisterId' : IDL.Text,
    'appVersion' : IDL.Text,
    'totalStorageBytes' : IDL.Nat,
    'backendCanisterId' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const FileMove = IDL.Record({
    'id' : IDL.Text,
    'isFolder' : IDL.Bool,
    'newParentId' : IDL.Opt(IDL.Text),
  });
  const InviteResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const FolderSearchResults = IDL.Record({
    'files' : IDL.Vec(FileMetadata),
    'folders' : IDL.Vec(FolderMetadata),
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__adminPrincipal' : IDL.Func([], [IDL.Reserved], ['query']),
    '__apiKeys' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, ApiKey))],
        ['query'],
      ),
    '__appVersion' : IDL.Func([], [IDL.Text], ['query']),
    '__approvalState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__backendCanisterId' : IDL.Func([], [IDL.Text], ['query']),
    '__cliFileBytes' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Nat8)))],
        ['query'],
      ),
    '__encryptedFiles' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    '__files' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, FileMetadata))],
        ['query'],
      ),
    '__firstAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    '__folders' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, FolderMetadata))],
        ['query'],
      ),
    '__frontendCanisterId' : IDL.Func([], [IDL.Text], ['query']),
    '__inviteCodes' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, InviteCode))],
        ['query'],
      ),
    '__nextApiKeyId' : IDL.Func([], [IDL.Nat], ['query']),
    '__nextFolderId' : IDL.Func([], [IDL.Nat], ['query']),
    '__tokenCounter' : IDL.Func([], [IDL.Nat], ['query']),
    '__userProfiles' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addFile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          ExternalBlob,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAccess' : IDL.Func([], [AccessCheckResult], ['query']),
    'createFolder' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Text], []),
    'deleteApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteFile' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteFolder' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'generateApiKey' : IDL.Func([IDL.Text], [IDL.Text], []),
    'generateInviteCode' : IDL.Func(
        [IDL.Opt(IDL.Int), IDL.Opt(IDL.Nat)],
        [IDL.Text],
        [],
      ),
    'getAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getAllFolders' : IDL.Func([], [IDL.Vec(FolderMetadata)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFile' : IDL.Func([IDL.Text], [IDL.Opt(FileMetadata)], ['query']),
    'getFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getFolder' : IDL.Func([IDL.Text], [IDL.Opt(FolderMetadata)], ['query']),
    'getFolderContents' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(FileSystemItem)],
        ['query'],
      ),
    'getMembers' : IDL.Func([], [IDL.Vec(AdminInfo)], ['query']),
    'getStorageStats' : IDL.Func([], [StorageStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([], [UserRole], ['query']),
    'http_request' : IDL.Func(
        [
          IDL.Record({
            'url' : IDL.Text,
            'method' : IDL.Text,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          }),
        ],
        [
          IDL.Record({
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
            'upgrade' : IDL.Opt(IDL.Bool),
            'status_code' : IDL.Nat16,
          }),
        ],
        ['query'],
      ),
    'http_request_update' : IDL.Func(
        [
          IDL.Record({
            'url' : IDL.Text,
            'method' : IDL.Text,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          }),
        ],
        [
          IDL.Record({
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
            'status_code' : IDL.Nat16,
          }),
        ],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isUsernameUnique' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'listApiKeys' : IDL.Func([], [IDL.Vec(ApiKey)], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'moveItem' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text), IDL.Bool], [], []),
    'moveItems' : IDL.Func([IDL.Vec(FileMove)], [], []),
    'redeemInviteCode' : IDL.Func([IDL.Text], [InviteResult], []),
    'removeMember' : IDL.Func([IDL.Principal], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'revokeInviteCode' : IDL.Func([IDL.Text], [InviteResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchFiles' : IDL.Func([IDL.Text], [IDL.Vec(FileMetadata)], ['query']),
    'searchFoldersInSubtree' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [FolderSearchResults],
        ['query'],
      ),
    'searchSubtree' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(FileSystemItem)],
        ['query'],
      ),
    'setAdmin' : IDL.Func([IDL.Principal], [InviteResult], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setBackendCanisterId' : IDL.Func([IDL.Text], [], []),
    'setFrontendCanisterId' : IDL.Func([IDL.Text], [], []),
    'validateInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };