/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccessCheckResult = { 'NeedsInvite' : null } |
  { 'Approved' : null } |
  { 'Admin' : null } |
  { 'PendingApproval' : null };
export interface AdminInfo {
  'principal' : Principal,
  'username' : string,
  'role' : UserRole,
}
export interface ApiKey {
  'id' : string,
  'token' : string,
  'ownerId' : Principal,
  'createdAt' : Time,
  'description' : string,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface FileMetadata {
  'id' : string,
  'ownerId' : Principal,
  'blob' : ExternalBlob,
  'name' : string,
  'createdAt' : Time,
  'size' : bigint,
  'updatedAt' : Time,
  'parentId' : [] | [string],
}
export interface FileMove {
  'id' : string,
  'isFolder' : boolean,
  'newParentId' : [] | [string],
}
export type FileSystemItem = { 'file' : FileMetadata } |
  { 'folder' : FolderMetadata };
export interface FolderMetadata {
  'id' : string,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'parentId' : [] | [string],
}
export interface FolderSearchResults {
  'files' : Array<FileMetadata>,
  'folders' : Array<FolderMetadata>,
}
export interface InviteCode {
  'expiresAt' : [] | [Time],
  'code' : string,
  'usedBy' : Array<Principal>,
  'createdAt' : Time,
  'createdBy' : Principal,
  'usedCount' : bigint,
  'isActive' : boolean,
  'maxUses' : [] | [bigint],
}
export type InviteResult = { 'ok' : null } |
  { 'err' : string };
export type Result = { 'ok' : null } |
  { 'err' : Error };
export interface StorageStats {
  'totalFiles' : bigint,
  'totalFolders' : bigint,
  'totalEncryptedFiles' : bigint,
  'frontendCanisterId' : string,
  'appVersion' : string,
  'totalStorageBytes' : bigint,
  'backendCanisterId' : string,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__adminPrincipal' : ActorMethod<[], any>,
  '__apiKeys' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, ApiKey]>
  >,
  '__appVersion' : ActorMethod<[], string>,
  '__approvalState' : ActorMethod<[], any>,
  '__backendCanisterId' : ActorMethod<[], string>,
  '__cliFileBytes' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, Uint8Array]>
  >,
  '__encryptedFiles' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, boolean]>
  >,
  '__files' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, FileMetadata]>
  >,
  '__firstAdmin' : ActorMethod<[], [] | [Principal]>,
  '__folders' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, FolderMetadata]>
  >,
  '__frontendCanisterId' : ActorMethod<[], string>,
  '__inviteCodes' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, InviteCode]>
  >,
  '__nextApiKeyId' : ActorMethod<[], bigint>,
  '__nextFolderId' : ActorMethod<[], bigint>,
  '__tokenCounter' : ActorMethod<[], bigint>,
  '__userProfiles' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, UserProfile]>
  >,
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addFile' : ActorMethod<
    [string, string, bigint, [] | [string], ExternalBlob, boolean],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAccess' : ActorMethod<[], AccessCheckResult>,
  'createFolder' : ActorMethod<[string, [] | [string]], string>,
  'deleteApiKey' : ActorMethod<[string], boolean>,
  'deleteFile' : ActorMethod<[string], boolean>,
  'deleteFolder' : ActorMethod<[string], boolean>,
  'generateApiKey' : ActorMethod<[string], string>,
  'generateInviteCode' : ActorMethod<[[] | [bigint], [] | [bigint]], string>,
  'getAdmin' : ActorMethod<[], [] | [Principal]>,
  'getAllFolders' : ActorMethod<[], Array<FolderMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFile' : ActorMethod<[string], [] | [FileMetadata]>,
  'getFiles' : ActorMethod<[], Array<FileMetadata>>,
  'getFolder' : ActorMethod<[string], [] | [FolderMetadata]>,
  'getFolderContents' : ActorMethod<[[] | [string]], Array<FileSystemItem>>,
  'getMembers' : ActorMethod<[], Array<AdminInfo>>,
  'getStorageStats' : ActorMethod<[], StorageStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[], UserRole>,
  'http_request' : ActorMethod<
    [
      {
        'url' : string,
        'method' : string,
        'body' : Uint8Array,
        'headers' : Array<[string, string]>,
      },
    ],
    {
      'body' : Uint8Array,
      'headers' : Array<[string, string]>,
      'upgrade' : [] | [boolean],
      'status_code' : number,
    }
  >,
  'http_request_update' : ActorMethod<
    [
      {
        'url' : string,
        'method' : string,
        'body' : Uint8Array,
        'headers' : Array<[string, string]>,
      },
    ],
    {
      'body' : Uint8Array,
      'headers' : Array<[string, string]>,
      'status_code' : number,
    }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isUsernameUnique' : ActorMethod<[string], boolean>,
  'listApiKeys' : ActorMethod<[], Array<ApiKey>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'moveItem' : ActorMethod<[string, [] | [string], boolean], undefined>,
  'moveItems' : ActorMethod<[Array<FileMove>], undefined>,
  'redeemInviteCode' : ActorMethod<[string], InviteResult>,
  'removeMember' : ActorMethod<[Principal], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'revokeInviteCode' : ActorMethod<[string], InviteResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchFiles' : ActorMethod<[string], Array<FileMetadata>>,
  'searchFoldersInSubtree' : ActorMethod<
    [string, [] | [string]],
    FolderSearchResults
  >,
  'searchSubtree' : ActorMethod<[string, [] | [string]], Array<FileSystemItem>>,
  'setAdmin' : ActorMethod<[Principal], InviteResult>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setBackendCanisterId' : ActorMethod<[string], undefined>,
  'setFrontendCanisterId' : ActorMethod<[string], undefined>,
  'validateInviteCode' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];