/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type Time = bigint;
export interface FileMetadata {
    id: string;
    ownerId: Principal;
    blob: ExternalBlob;
    name: string;
    createdAt: Time;
    size: bigint;
    updatedAt: Time;
    parentId?: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FolderSearchResults {
    files: Array<FileMetadata>;
    folders: Array<FolderMetadata>;
}
export type FileSystemItem = {
    __kind__: "file";
    file: FileMetadata;
} | {
    __kind__: "folder";
    folder: FolderMetadata;
};
export interface FolderMetadata {
    id: string;
    ownerId: Principal;
    name: string;
    createdAt: Time;
    updatedAt: Time;
    parentId?: string;
}
export interface InviteCode {
    expiresAt?: Time;
    code: string;
    usedBy: Array<Principal>;
    createdAt: Time;
    createdBy: Principal;
    usedCount: bigint;
    isActive: boolean;
    maxUses?: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface ApiKey {
    id: string;
    token: string;
    ownerId: Principal;
    createdAt: Time;
    description: string;
}
export interface AdminInfo {
    principal: Principal;
    username: string;
    role: UserRole;
}
export interface FileMove {
    id: string;
    isFolder: boolean;
    newParentId?: string;
}
export type InviteResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface UserProfile {
    name: string;
}
export interface StorageStats {
    totalFiles: bigint;
    totalFolders: bigint;
    totalEncryptedFiles: bigint;
    frontendCanisterId: string;
    appVersion: string;
    totalStorageBytes: bigint;
    backendCanisterId: string;
}
export enum AccessCheckResult {
    NeedsInvite = "NeedsInvite",
    Approved = "Approved",
    Admin = "Admin",
    PendingApproval = "PendingApproval"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    __accessControlState(): Promise<any>;
    __adminPrincipal(): Promise<any>;
    __apiKeys(ko: string | null, count: bigint | null): Promise<Array<[string, ApiKey]>>;
    __appVersion(): Promise<string>;
    __approvalState(): Promise<any>;
    __backendCanisterId(): Promise<string>;
    __cliFileBytes(ko: string | null, count: bigint | null): Promise<Array<[string, Uint8Array]>>;
    __encryptedFiles(ko: string | null, count: bigint | null): Promise<Array<[string, boolean]>>;
    __files(ko: string | null, count: bigint | null): Promise<Array<[string, FileMetadata]>>;
    __firstAdmin(): Promise<Principal | null>;
    __folders(ko: string | null, count: bigint | null): Promise<Array<[string, FolderMetadata]>>;
    __frontendCanisterId(): Promise<string>;
    __inviteCodes(ko: string | null, count: bigint | null): Promise<Array<[string, InviteCode]>>;
    __nextApiKeyId(): Promise<bigint>;
    __nextFolderId(): Promise<bigint>;
    __tokenCounter(): Promise<bigint>;
    __userProfiles(ko: Principal | null, count: bigint | null): Promise<Array<[Principal, UserProfile]>>;
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addFile(id: string, name: string, size: bigint, parentId: string | null, blob: ExternalBlob, isEncrypted: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkAccess(): Promise<AccessCheckResult>;
    createFolder(name: string, parentId: string | null): Promise<string>;
    deleteApiKey(id: string): Promise<boolean>;
    deleteFile(id: string): Promise<boolean>;
    deleteFolder(id: string): Promise<boolean>;
    generateApiKey(description: string): Promise<string>;
    generateInviteCode(expiresAt: bigint | null, maxUses: bigint | null): Promise<string>;
    getAdmin(): Promise<Principal | null>;
    getAllFolders(): Promise<Array<FolderMetadata>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFile(id: string): Promise<FileMetadata | null>;
    getFiles(): Promise<Array<FileMetadata>>;
    getFolder(id: string): Promise<FolderMetadata | null>;
    getFolderContents(folderId: string | null): Promise<Array<FileSystemItem>>;
    getMembers(): Promise<Array<AdminInfo>>;
    getStorageStats(): Promise<StorageStats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRole(): Promise<UserRole>;
    http_request(req: {
        url: string;
        method: string;
        body: Uint8Array;
        headers: Array<[string, string]>;
    }): Promise<{
        body: Uint8Array;
        headers: Array<[string, string]>;
        upgrade?: boolean;
        status_code: number;
    }>;
    http_request_update(req: {
        url: string;
        method: string;
        body: Uint8Array;
        headers: Array<[string, string]>;
    }): Promise<{
        body: Uint8Array;
        headers: Array<[string, string]>;
        status_code: number;
    }>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isUsernameUnique(username: string): Promise<boolean>;
    listApiKeys(): Promise<Array<ApiKey>>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listInviteCodes(): Promise<Array<InviteCode>>;
    moveItem(itemId: string, newParentId: string | null, isFolder: boolean): Promise<void>;
    moveItems(moves: Array<FileMove>): Promise<void>;
    redeemInviteCode(code: string): Promise<InviteResult>;
    removeMember(principal: Principal): Promise<void>;
    requestApproval(): Promise<void>;
    revokeInviteCode(code: string): Promise<InviteResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchFiles(searchTerm: string): Promise<Array<FileMetadata>>;
    searchFoldersInSubtree(searchTerm: string, startFolderId: string | null): Promise<FolderSearchResults>;
    searchSubtree(searchTerm: string, startFolderId: string | null): Promise<Array<FileSystemItem>>;
    setAdmin(principal: Principal): Promise<InviteResult>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setBackendCanisterId(canisterId: string): Promise<void>;
    setFrontendCanisterId(canisterId: string): Promise<void>;
    validateInviteCode(code: string): Promise<boolean>;
}
import type { AccessCheckResult as _AccessCheckResult, AdminInfo as _AdminInfo, ApprovalStatus as _ApprovalStatus, Error as _Error, ExternalBlob as _ExternalBlob, FileMetadata as _FileMetadata, FileMove as _FileMove, FileSystemItem as _FileSystemItem, FolderMetadata as _FolderMetadata, FolderSearchResults as _FolderSearchResults, InviteCode as _InviteCode, InviteResult as _InviteResult, Result as _Result, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __adminPrincipal(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__adminPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__adminPrincipal();
            return result;
        }
    }
    async __apiKeys(arg0: string | null, arg1: bigint | null): Promise<Array<[string, ApiKey]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__apiKeys(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__apiKeys(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __appVersion(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.__appVersion();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__appVersion();
            return result;
        }
    }
    async __approvalState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__approvalState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__approvalState();
            return result;
        }
    }
    async __backendCanisterId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.__backendCanisterId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__backendCanisterId();
            return result;
        }
    }
    async __cliFileBytes(arg0: string | null, arg1: bigint | null): Promise<Array<[string, Uint8Array]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__cliFileBytes(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__cliFileBytes(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __encryptedFiles(arg0: string | null, arg1: bigint | null): Promise<Array<[string, boolean]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__encryptedFiles(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__encryptedFiles(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __files(arg0: string | null, arg1: bigint | null): Promise<Array<[string, FileMetadata]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__files(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__files(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async __firstAdmin(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.__firstAdmin();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__firstAdmin();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async __folders(arg0: string | null, arg1: bigint | null): Promise<Array<[string, FolderMetadata]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__folders(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__folders(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async __frontendCanisterId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.__frontendCanisterId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__frontendCanisterId();
            return result;
        }
    }
    async __inviteCodes(arg0: string | null, arg1: bigint | null): Promise<Array<[string, InviteCode]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__inviteCodes(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__inviteCodes(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async __nextApiKeyId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextApiKeyId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextApiKeyId();
            return result;
        }
    }
    async __nextFolderId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextFolderId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextFolderId();
            return result;
        }
    }
    async __tokenCounter(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__tokenCounter();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__tokenCounter();
            return result;
        }
    }
    async __userProfiles(arg0: Principal | null, arg1: bigint | null): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__userProfiles(to_candid_opt_n20(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__userProfiles(to_candid_opt_n20(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addFile(arg0: string, arg1: string, arg2: bigint, arg3: string | null, arg4: ExternalBlob, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFile(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), await to_candid_ExternalBlob_n31(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFile(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), await to_candid_ExternalBlob_n31(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkAccess(): Promise<AccessCheckResult> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAccess();
                return from_candid_AccessCheckResult_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAccess();
            return from_candid_AccessCheckResult_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFolder(arg0: string, arg1: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createFolder(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFolder(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteApiKey(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteApiKey(arg0);
            return result;
        }
    }
    async deleteFile(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFile(arg0);
            return result;
        }
    }
    async deleteFolder(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFolder(arg0);
            return result;
        }
    }
    async generateApiKey(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateApiKey(arg0);
            return result;
        }
    }
    async generateInviteCode(arg0: bigint | null, arg1: bigint | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode(to_candid_opt_n36(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode(to_candid_opt_n36(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAdmin(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdmin();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdmin();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFolders(): Promise<Array<FolderMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFolders();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFolders();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFile(arg0: string): Promise<FileMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFile(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFile(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFiles(): Promise<Array<FileMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFiles();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFiles();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFolder(arg0: string): Promise<FolderMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFolder(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFolder(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFolderContents(arg0: string | null): Promise<Array<FileSystemItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFolderContents(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFolderContents(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembers(): Promise<Array<AdminInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembers();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembers();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStorageStats(): Promise<StorageStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStorageStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStorageStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async http_request(arg0: {
        url: string;
        method: string;
        body: Uint8Array;
        headers: Array<[string, string]>;
    }): Promise<{
        body: Uint8Array;
        headers: Array<[string, string]>;
        upgrade?: boolean;
        status_code: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.http_request(arg0);
                return from_candid_record_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.http_request(arg0);
            return from_candid_record_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async http_request_update(arg0: {
        url: string;
        method: string;
        body: Uint8Array;
        headers: Array<[string, string]>;
    }): Promise<{
        body: Uint8Array;
        headers: Array<[string, string]>;
        status_code: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.http_request_update(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.http_request_update(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isUsernameUnique(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsernameUnique(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsernameUnique(arg0);
            return result;
        }
    }
    async listApiKeys(): Promise<Array<ApiKey>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApiKeys();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApiKeys();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInviteCodes();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInviteCodes();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async moveItem(arg0: string, arg1: string | null, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moveItem(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveItem(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async moveItems(arg0: Array<FileMove>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moveItems(to_candid_vec_n57(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveItems(to_candid_vec_n57(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async redeemInviteCode(arg0: string): Promise<InviteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemInviteCode(arg0);
                return from_candid_InviteResult_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemInviteCode(arg0);
            return from_candid_InviteResult_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeMember(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMember(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async revokeInviteCode(arg0: string): Promise<InviteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeInviteCode(arg0);
                return from_candid_InviteResult_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeInviteCode(arg0);
            return from_candid_InviteResult_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchFiles(arg0: string): Promise<Array<FileMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFiles(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFiles(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchFoldersInSubtree(arg0: string, arg1: string | null): Promise<FolderSearchResults> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFoldersInSubtree(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_FolderSearchResults_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFoldersInSubtree(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_FolderSearchResults_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchSubtree(arg0: string, arg1: string | null): Promise<Array<FileSystemItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchSubtree(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchSubtree(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAdmin(arg0: Principal): Promise<InviteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin(arg0);
                return from_candid_InviteResult_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin(arg0);
            return from_candid_InviteResult_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n64(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n64(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setBackendCanisterId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBackendCanisterId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBackendCanisterId(arg0);
            return result;
        }
    }
    async setFrontendCanisterId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFrontendCanisterId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFrontendCanisterId(arg0);
            return result;
        }
    }
    async validateInviteCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateInviteCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateInviteCode(arg0);
            return result;
        }
    }
}
function from_candid_AccessCheckResult_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccessCheckResult): AccessCheckResult {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_AdminInfo_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminInfo): AdminInfo {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FileMetadata_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileMetadata): Promise<FileMetadata> {
    return await from_candid_record_n6(_uploadFile, _downloadFile, value);
}
async function from_candid_FileSystemItem_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileSystemItem): Promise<FileSystemItem> {
    return await from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_FolderMetadata_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FolderMetadata): FolderMetadata {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_FolderSearchResults_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FolderSearchResults): Promise<FolderSearchResults> {
    return await from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_InviteCode_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InviteCode): InviteCode {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_InviteResult_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InviteResult): InviteResult {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileMetadata]): Promise<FileMetadata | null> {
    return value.length === 0 ? null : await from_candid_FileMetadata_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FolderMetadata]): FolderMetadata | null {
    return value.length === 0 ? null : from_candid_FolderMetadata_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    ownerId: Principal;
    name: string;
    createdAt: _Time;
    updatedAt: _Time;
    parentId: [] | [string];
}): {
    id: string;
    ownerId: Principal;
    name: string;
    createdAt: Time;
    updatedAt: Time;
    parentId?: string;
} {
    return {
        id: value.id,
        ownerId: value.ownerId,
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        parentId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.parentId))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiresAt: [] | [_Time];
    code: string;
    usedBy: Array<Principal>;
    createdAt: _Time;
    createdBy: Principal;
    usedCount: bigint;
    isActive: boolean;
    maxUses: [] | [bigint];
}): {
    expiresAt?: Time;
    code: string;
    usedBy: Array<Principal>;
    createdAt: Time;
    createdBy: Principal;
    usedCount: bigint;
    isActive: boolean;
    maxUses?: bigint;
} {
    return {
        expiresAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.expiresAt)),
        code: value.code,
        usedBy: value.usedBy,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        usedCount: value.usedCount,
        isActive: value.isActive,
        maxUses: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.maxUses))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    username: string;
    role: _UserRole;
}): {
    principal: Principal;
    username: string;
    role: UserRole;
} {
    return {
        principal: value.principal,
        username: value.username,
        role: from_candid_UserRole_n39(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    body: Uint8Array;
    headers: Array<[string, string]>;
    upgrade: [] | [boolean];
    status_code: number;
}): {
    body: Uint8Array;
    headers: Array<[string, string]>;
    upgrade?: boolean;
    status_code: number;
} {
    return {
        body: value.body,
        headers: value.headers,
        upgrade: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.upgrade)),
        status_code: value.status_code
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n54(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
async function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    ownerId: Principal;
    blob: _ExternalBlob;
    name: string;
    createdAt: _Time;
    size: bigint;
    updatedAt: _Time;
    parentId: [] | [string];
}): Promise<{
    id: string;
    ownerId: Principal;
    blob: ExternalBlob;
    name: string;
    createdAt: Time;
    size: bigint;
    updatedAt: Time;
    parentId?: string;
}> {
    return {
        id: value.id,
        ownerId: value.ownerId,
        blob: await from_candid_ExternalBlob_n7(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        createdAt: value.createdAt,
        size: value.size,
        updatedAt: value.updatedAt,
        parentId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.parentId))
    };
}
async function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    files: Array<_FileMetadata>;
    folders: Array<_FolderMetadata>;
}): Promise<{
    files: Array<FileMetadata>;
    folders: Array<FolderMetadata>;
}> {
    return {
        files: await from_candid_vec_n42(_uploadFile, _downloadFile, value.files),
        folders: from_candid_vec_n37(_uploadFile, _downloadFile, value.folders)
    };
}
function from_candid_tuple_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _FolderMetadata]): [string, FolderMetadata] {
    return [
        value[0],
        from_candid_FolderMetadata_n12(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _InviteCode]): [string, InviteCode] {
    return [
        value[0],
        from_candid_InviteCode_n16(_uploadFile, _downloadFile, value[1])
    ];
}
async function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _FileMetadata]): Promise<[string, FileMetadata]> {
    return [
        value[0],
        await from_candid_FileMetadata_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n29(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    NeedsInvite: null;
} | {
    Approved: null;
} | {
    Admin: null;
} | {
    PendingApproval: null;
}): AccessCheckResult {
    return "NeedsInvite" in value ? AccessCheckResult.NeedsInvite : "Approved" in value ? AccessCheckResult.Approved : "Admin" in value ? AccessCheckResult.Admin : "PendingApproval" in value ? AccessCheckResult.PendingApproval : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    file: _FileMetadata;
} | {
    folder: _FolderMetadata;
}): Promise<{
    __kind__: "file";
    file: FileMetadata;
} | {
    __kind__: "folder";
    folder: FolderMetadata;
}> {
    return "file" in value ? {
        __kind__: "file",
        file: await from_candid_FileMetadata_n5(_uploadFile, _downloadFile, value.file)
    } : "folder" in value ? {
        __kind__: "folder",
        folder: from_candid_FolderMetadata_n12(_uploadFile, _downloadFile, value.folder)
    } : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _FolderMetadata]>): Array<[string, FolderMetadata]> {
    return value.map((x)=>from_candid_tuple_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _InviteCode]>): Array<[string, InviteCode]> {
    return value.map((x)=>from_candid_tuple_n15(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _FileMetadata]>): Promise<Array<[string, FileMetadata]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n4(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FolderMetadata>): Array<FolderMetadata> {
    return value.map((x)=>from_candid_FolderMetadata_n12(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileMetadata>): Promise<Array<FileMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FileMetadata_n5(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileSystemItem>): Promise<Array<FileSystemItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FileSystemItem_n45(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminInfo>): Array<AdminInfo> {
    return value.map((x)=>from_candid_AdminInfo_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InviteCode>): Array<InviteCode> {
    return value.map((x)=>from_candid_InviteCode_n16(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FileMove_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileMove): _FileMove {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n22(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    isFolder: boolean;
    newParentId?: string;
}): {
    id: string;
    isFolder: boolean;
    newParentId: [] | [string];
} {
    return {
        id: value.id,
        isFolder: value.isFolder,
        newParentId: value.newParentId ? candid_some(value.newParentId) : candid_none()
    };
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FileMove>): Array<_FileMove> {
    return value.map((x)=>to_candid_FileMove_n58(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
